repos:
 # Run ruff first because autofix behaviour is enabled
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.1.3
   hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 23.10.1
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py38
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: 5.12.0
   hooks:
    - id: isort-conda
      additional_dependencies: [-c, conda-forge, toml=0.10.2]
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: "1.6.1"
   hooks:
    - id: mypy-conda
      additional_dependencies:
        - -c
        - conda-forge
        - types-mock
        - types-setuptools
        - types-redis
        - types-boto
        - boto3-stubs
 - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
   rev: 3.15.0
   hooks:
    - id: pyupgrade-conda
      args:
        - --py38-plus
